apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-mock
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    owner: {{ .Values.owner }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: http-mock
    spec:
      containers:
      - name: mock-http-server
        image: deis/mock-http-server
        ports:
          - containerPort: 8080
          - protocol: TCP
