apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mock-http.fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    owner: {{ .Values.owner }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: http-mock
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecretNane }}
      containers:
      - name: mock-http-server
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
